Feature/support ssl policy in https load balanccer
gruntwork-io/terraform-google-load-balancer pull request #15
Opened 2020-06-17 23:51 UTC by romankor

Adding the ability to provide custom SSL policy to HTTP load balancer

2020-06-25 20:49 UTC, romankor commented
@robmorgan ?

2020-11-12 04:40 UTC, robmorgan requested changes
@romankor sorry for the delay! As a company, we've prioritized our AWS products during the pandemic this year and unfortunately, we have been **super slow** to respond to GCP issues. I've left some quick feedback on the PR. We should also add an explicit [test case](https://terratest.gruntwork.io) for this functionality to ensure it works correctly. Are you able to do this?

2020-11-12 04:40 UTC, robmorgan commented on modules/http-load-balancer/variables.tf
> +  default     = ""
```suggestion
  default     = null
```
Let's set the default to `null` for better consistency with our other modules.

2020-11-12 04:40 UTC, robmorgan commented on modules/http-load-balancer/variables.tf
> +  description = "Link to ssl policy. Omitted if not provided"
```suggestion
  description = "A reference to the SslPolicy resource that will be associated with the TargetHttpsProxy resource. If not set, the TargetHttpsProxy resource will not have any SSL policy configured."
```
We'll adopt the TF provider docs as its clearer to the users.

2020-12-04 05:25 UTC, romankor commented
> @romankor sorry for the delay! As a company, we've prioritized our AWS products during the pandemic this year and unfortunately, we have been **super slow** to respond to GCP issues. I've left some quick feedback on the PR. We should also add an explicit [test case](https://terratest.gruntwork.io) for this functionality to ensure it works correctly. Are you able to do this?

@robmorgan 
fixed ,  any chances you guys will merge it now ?

2020-12-04 07:09 UTC, robmorgan commented
Hi @romankor you will still need to add an explicit test case using [Terratest](https://terratest.gruntwork.io) so we can test this feature.. Are you able to do this?

2023-03-29 16:30 UTC, MoonMoon1919 commented
Closing this PR as it has been two years since last update and this repo has been in "sunsetting" for one year.

---

### Sunset notice
We believe there is an opportunity to create a truly outstanding developer experience for deploying to the cloud, however developing this vision requires that we temporarily limit our focus to just one cloud. Gruntwork has hundreds of customers currently using AWS, so we have temporarily suspended our maintenance efforts on this repo. Once we have implemented and validated our vision for the developer experience on the cloud, we look forward to picking this up. In the meantime, you are welcome to use this code in accordance with the open source license, however we will not be responding to GitHub Issues or Pull Requests.

If you wish to be the maintainer for this project, we are open to considering that. Please contact us at [support@gruntwork.io](mailto:support@gruntwork.io)

2023-03-29 16:30 UTC, closed without merging